apps/clients/urls.py
from django.urls import path

from apps.newsletters.apps import NewsletterConfig
from apps.clients.views import (ClientsListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                                ClientDeleteView, AddClientsToNewsletterView)

app_name = NewsletterConfig.name

urlpatterns = [
    path('clients/', ClientsListView.as_view(), name='clients_list'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('newsletters/<int:newsletter_id>/add_clients/', AddClientsToNewsletterView.as_view(),
         name='add_clients'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.newsletters.urls', namespace='newsletters')),
    path('', include('apps.users.urls', namespace='users')),
    path('', include('apps.clients.urls', namespace='clients')),
    path('', include('apps.messages_.urls', namespace='messages_')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clients/models.py
from django.db import models

from apps.blog.models import NULLABLE
from config import settings


class Clients(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=50, verbose_name='Отчество')
    email = models.EmailField(max_length=100, verbose_name='Email')
    comment = models.TextField(max_length=200, **NULLABLE, verbose_name="Комментарий")
    birthday = models.DateField(**NULLABLE, verbose_name='День рождения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='owner',
                              **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.middle_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['first_name', 'last_name', 'middle_name']
        unique_together = ['email', 'owner']
        db_table = '_cl_clients'
        db_table_comment = "Клиенты"
        permissions = [
            ('view_all_clients', 'Can view all Клиент'),
        ]

apps/clients/forms.py
from django import forms

from apps.clients.models import Clients
from apps.newsletters.models import Newsletters
from core.forms import StyleFormMixin


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Clients
        exclude = ('owner',)


class AddClientsToNewsletterForm(forms.Form):

    newsletter = forms.ModelChoiceField(queryset=Newsletters.objects.all(), label='Рассылка')
    clients = forms.ModelMultipleChoiceField(queryset=Clients.objects.all(), label='Клиенты',
                                             widget=forms.CheckboxSelectMultiple)

apps/clients/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView

from django.urls import reverse, reverse_lazy
from apps.clients.forms import ClientForm, AddClientsToNewsletterForm
from apps.clients.models import Clients


class ClientsListView(PermissionRequiredMixin, ListView):
    model = Clients
    template_name = 'clients/clients_list.html'
    extra_context = {'title': 'Клиенты'}
    login_url = reverse_lazy('users:login')
    permission_required = ('clients.view_clients',)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or user.has_perm('clients.view_all_clients'):
            return queryset
        else:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientDetailView(PermissionRequiredMixin, DetailView):
    model = Clients
    template_name = 'clients/client_detail.html'
    extra_context = {'title': 'Клиент'}
    login_url = reverse_lazy('users:login')
    permission_required = ('clients.view_clients',)

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists() or object.owner == user:
            return object
        else:
            raise PermissionDenied


class ClientCreateView(PermissionRequiredMixin, CreateView):
    model = Clients
    form_class = ClientForm
    template_name = 'clients/client_form.html'
    extra_context = {'title': 'Создать клиента'}
    login_url = reverse_lazy('users:login')
    permission_required = ('clients.add_clients',)

    def get_success_url(self):
        return reverse('clients:client', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(PermissionRequiredMixin, UpdateView):
    model = Clients
    form_class = ClientForm
    template_name = 'clients/client_form.html'
    extra_context = {'title': 'Редактировать клиента'}
    login_url = reverse_lazy('users:login')
    permission_required = ('clients.change_clients',)

    def get_success_url(self):
        return reverse('clients:client', kwargs={'pk': self.object.pk})

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.owner == user:
            return object
        else:
            raise PermissionDenied


class ClientDeleteView(PermissionRequiredMixin, DeleteView):
    model = Clients
    template_name = 'clients/client_confirm_delete.html'
    extra_context = {'title': 'Удалить клиента'}
    success_url = reverse_lazy('clients:clients_list')
    login_url = reverse_lazy('users:login')
    permission_required = ('clients.delete_clients', 'clients.change_clients',)

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.owner == user:
            return object
        else:
            raise PermissionDenied


class AddClientsToNewsletterView(PermissionRequiredMixin, FormView):
    template_name = 'clients/add_clients.html'
    form_class = AddClientsToNewsletterForm
    success_url = reverse_lazy('newsletters:newsletters_list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

apps/clients/templates/clients/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center text-center">
        <div class="col-7">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                <p>
                    Желаете удалить клиента {{ object.first_name}} {{ object.last_name }} {{ object.middle_name }}?
                </p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'clients:client' object.pk %}" class="btn btn-warning">Отмена</a>
            </form>
        </div>

        <div class="col-7">
            <div class="card">
                <div class="card-header">
                    {{ object.first_name }} {{ object.last_name }} {{ object.middle_name }}
                </div>
                <div class="card-body text-start">
                    <ul>
                        <li>Email: {{ object.email }}</li>
                        <li>Комментарий: {{ object.comment }}</li>
                        <li>День рождения: {{ object.birthday }}</li>
                    </ul>
                </div>
            </div>
            <div class="col-xxl-4"></div>
        </div>
    </div>
    <div class="col-xxl-3"></div>
</div>
</div>


{% endblock content %}

apps/clients/templates/clients/client_detail.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xxl-2">
            <div class="btn-group" role="group" aria-label="Basic outlined button group">
                {% if perms.clients.change_clients and user == object.owner %}
                <button type="button" class="btn btn-outline-primary shadow-sm">
                    <a href="{% url 'clients:update_client' object.pk %}">Изменить</a>
                </button>
                {% endif %}
                {% if perms.clients.delete_clients and user == object.owner %}
                <button type="button" class="btn btn-outline-primary shadow-sm">
                    <a href="{% url 'clients:delete_client' object.pk %}">Удалить</a>
                </button>
                {% endif %}
            </div>
        </div>

        <div class="col-xxl-3">
        </div>

        <div class="col-xxl-7">
            <div class="card">
                <div class="card-header text-center">
                    {{ object.first_name }} {{ object.last_name }} {{ object.middle_name }}
                </div>
                <div class="card-body">
                    <ul>
                        <li>Email: {{ object.email }}</li>
                        <li>Комментарий: {{ object.comment }}</li>
                        <li>День рождения: {{ object.birthday }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/clients/templates/clients/client_form.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-xxl-3"></div>
        <div class="col-xxl-5">
            <p class="fs-4 text-center">
                Форма {% if object %}редактирования{% else %}создания{% endif %} клиента
            </p>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn-outline-primary" type="submit">
                    {% if object %} Изменить {% else %} Добавить {% endif %}
                </button>
                {% if object %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'clients:client' object.pk %}'">
                    Отмена
                </button>
                {% else %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'clients:clients_list' %}'">
                    Отмена
                </button>
                {% endif %}

            </form>
        </div>
        <div class="col-xxl-4"></div>
    </div>

</div>

{% endblock content %}

apps/clients/templates/clients/clients_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    {% if perms.clients.add_clients %}
    <button type="button" class="btn btn-outline-primary shadow-sm">
        <a href="{% url 'clients:create_client' %}" style="color: black; text-decoration: none;">Создать клиента</a>
    </button>
    {% endif %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            {% if perms.clients.view_all_clients %}
            <th scope="col">Пользователь (email)</th>
            <th scope="col">Пользователь (user name)</th>
            {% endif %}
            <th scope="col">Имя Фамилия Отчество</th>
            <th scope="col">Email</th>
            <th scope="col">Комментарий</th>
            <th scope="col">День рождения</th>
        </tr>
        </thead>
        {% for client in object_list %}
        <tbody>
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            {% if perms.clients.view_all_clients %}
            <td><a>{{ client.owner.email }}</a></td>
            <td><a>{{ client.owner.user_name }}</a></td>
            {% endif %}
            <td><a href="{% url 'clients:client' client.pk %}">
                {{ client.first_name }} {{ client.last_name }} {{ client.middle_name }}
            </a></td>
            <td>{{ client.email }}</td>
            <td>{{ client.comment }}</td>
            <td>{{ client.birthday }}</td>
        </tr>

        </tbody>
        {% endfor %}
    </table>
</div>

{% endblock content %}