apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.blog.apps import BlogConfig
from apps.blog.views import (ArticlesListView, ArticlesDetailView, ArticleCreateView, ArticleDeleteView,
                             ArticleUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path('news/', ArticlesListView.as_view(), name='articles_list'),
    path('news/create/', ArticleCreateView.as_view(), name='create_article'),
    path('news/<str:slug>/', cache_page(60)(ArticlesDetailView.as_view()), name='article'),
    path('news/edit/<str:slug>/', ArticleUpdateView.as_view(), name='update_article'),
    path('news/delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete_article'),

]

apps/clients/urls.py
from django.urls import path

from apps.newsletters.apps import NewsletterConfig
from apps.clients.views import (ClientsListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                                ClientDeleteView, AddClientsToNewsletterView)

app_name = NewsletterConfig.name

urlpatterns = [
    path('clients/', ClientsListView.as_view(), name='clients_list'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('newsletters/<int:newsletter_id>/add_clients/', AddClientsToNewsletterView.as_view(),
         name='add_clients'),
]

apps/main/urls.py
from django.urls import path

from apps.main.apps import MainConfig
from apps.main.views import HomeView, AboutView, ContactsView

app_name = MainConfig.name


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
]

apps/messages_/urls.py
from django.urls import path
from apps.messages_.apps import MessagesConfig
from apps.messages_.views import MessagesListView, MessageCreateView, MessageDetailView, MessageDeleteView, \
    MessageUpdateView

app_name = MessagesConfig.name


urlpatterns = [
    path('messages/', MessagesListView.as_view(), name='messages_list'),

    path('messages/<int:pk>', MessageDetailView.as_view(), name='message'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/update/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('messages/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

]

apps/users/urls.py
from django.urls import path

from apps.users.apps import UsersConfig
from apps.users.views import UserLoginView, UserLogoutView, UserRegisterView, ProfileView, UserPasswordResetView, \
    email_verification, toggle_activiti, ProfileUpdateView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/<int:pk>/', ProfileUpdateView.as_view(), name='update_profile'),
    path('confirm-email/<str:token>/', email_verification, name='confirm-email'),
    path('recovery/', UserPasswordResetView.as_view(), name='recovery'),
    path('toggle_activiti/<int:pk>/', toggle_activiti, name='toggle_activiti')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.newsletters.urls', namespace='newsletters')),
    path('', include('apps.users.urls', namespace='users')),
    path('', include('apps.clients.urls', namespace='clients')),
    path('', include('apps.messages_.urls', namespace='messages_')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/views.py
import logging
import random

from django.views.generic import TemplateView

from apps.blog.models import Articles
from core.services import get_random_articles, get_count_newsletters, get_count_active_newsletters, get_count_clients

logger = logging.getLogger(__name__)


class HomeView(TemplateView):
    template_name = 'main/home.html'
    extra_context = {'title': 'Главная'}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['random_articles_list'] = get_random_articles(4)
        context_data['count_newsletters'] = get_count_newsletters()
        context_data['count_active_newsletters'] = get_count_active_newsletters()
        context_data['count_clients'] = get_count_clients()
        return context_data


class AboutView(TemplateView):
    template_name = 'main/about.html'
    extra_context = {'title': 'О нас'}


class ContactsView(TemplateView):
    template_name = 'main/contacts.html'
    extra_context = {'title': 'Контакты'}

apps/main/templates/main/subtemplates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/main/templates/main/subtemplates/header.html
<nav class="navbar navbar-expand-md " aria-label="Fourth navbar example">
    <div class="container-xl">
        <a class="navbar-brand me-5" href="{% url 'main:home' %}">
            <h1 class="display-4 m-0">Сервис рассылок</h1>
            <p class="lead d-none d-md-block  m-0">Ваши письма — наша ответственность!</p>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
                aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--        Блок с основными ссылками-->
        <div class="collapse navbar-collapse align-content-between flex-wrap gap-2 " id="navbarsExample04">
            <div class="navbar-nav gap-2 ms-md-auto mb-4 mb-sm-1 mb-md-0">
                <a class="btn btn-outline-dark shadow-sm" href=" {% url 'blog:articles_list' %}">Новости</a>
                <a class="btn btn-outline-dark shadow-sm" href=" {% url 'main:contacts' %}">Контакты</a>
                <a class="btn btn-outline-dark shadow-sm" href=" {% url 'main:about' %}">О нас</a>
            </div>

            <!--            Блок для авторизованного пользователя с основными меню-->
            {% if user.is_authenticated %}
<!--            <div class="navbar-nav gap-2 ms-md-auto mb-4 mb-sm-1 mb-md-0">-->
                <a class="btn btn-outline-primary shadow-sm"
                   href=" {% url 'newsletters:newsletters_list' %}">Рассылки</a>
                <a class="btn btn-outline-primary shadow-sm"
                   href=" {% url 'clients:clients_list' %}">Клиенты</a>
                <a class="btn btn-outline-primary shadow-sm"
                   href=" {% url 'messages_:messages_list' %}">Сообщения</a>
<!--            </div>-->
            {% endif %}

            <!--            Блок входа, выхода и профиля-->
            {% if user.is_authenticated %}
            <div class="navbar-nav ms-md-auto gap-2">

                <!--            Если авторизован - профиль и выйти-->
                <a class="p-2 btn btn-warning mr-1" href="{% url 'users:profile' %}">
                    {{ user.email }}
                </a>
                <a>
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="p-2 btn btn-danger">Выйти</button>
                    </form>
                </a>

                {% else %}
                <!--            Если не авторизован - войти и зарегистрироваться-->
                <button class="btn btn-outline-primary " type="submit">
                    <a href="{% url 'users:login' %}">Войти</a>
                </button>
                <button class="btn btn-outline-success" type="submit">
                    <a href="{% url 'users:register' %}">Зарегистрироваться</a>
                </button>
            </div>

            {% endif %}
        </div>
    </div>
</nav>