apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from apps.blog.apps import BlogConfig
from apps.blog.views import (ArticlesListView, ArticlesDetailView, ArticleCreateView, ArticleDeleteView,
                             ArticleUpdateView)

app_name = BlogConfig.name


urlpatterns = [
    path('news/', ArticlesListView.as_view(), name='articles_list'),
    path('news/create/', ArticleCreateView.as_view(), name='create_article'),
    path('news/<str:slug>/', cache_page(60)(ArticlesDetailView.as_view()), name='article'),
    path('news/edit/<str:slug>/', ArticleUpdateView.as_view(), name='update_article'),
    path('news/delete/<str:slug>/', ArticleDeleteView.as_view(), name='delete_article'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.newsletters.urls', namespace='newsletters')),
    path('', include('apps.users.urls', namespace='users')),
    path('', include('apps.clients.urls', namespace='clients')),
    path('', include('apps.messages_.urls', namespace='messages_')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from pytils.translit import slugify

from config import settings


NULLABLE = {'null': True, 'blank': True}


class Articles(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название статьи")
    slug = models.CharField(max_length=100, null=True, blank=True, verbose_name="Slug статьи")
    text = models.TextField(verbose_name="Текст статьи")
    img = models.ImageField(upload_to='blog/news/', null=True, blank=True, verbose_name='Превью статьи',
                            default='blog/news/default.jpeg')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    is_published = models.BooleanField(default=False, verbose_name="Статус публикации")

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                               verbose_name='Пользователь')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            original_slug = self.slug
            queryset = Articles.objects.filter(slug=self.slug).exclude(pk=self.pk)
            counter = 1
            while queryset.exists():
                self.slug = f'{original_slug}-{counter}'
                counter += 1
                queryset = Articles.objects.filter(slug=self.slug).exclude(pk=self.pk)
        super().save(args, kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["-created_at"]
        db_table = '_bl_articles'
        db_table_comment = "Статьи"

apps/blog/forms.py
from django.forms import ModelForm
from core.forms import StyleFormMixin
from apps.blog.models import Articles


class ArticleForm(StyleFormMixin, ModelForm):

    class Meta:
        model = Articles
        fields = ('title', 'text', 'is_published')

apps/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from apps.blog.forms import ArticleForm
from apps.blog.models import Articles
from django.urls import reverse, reverse_lazy

from apps.blog.utils import get_article_list_from_cache


class ArticlesListView(ListView):
    model = Articles
    template_name = 'blog/articles_list.html'
    extra_context = {'title': 'Новости'}

    def get_queryset(self):
        return get_article_list_from_cache()


class ArticlesDetailView(DetailView):
    model = Articles
    template_name = 'blog/article_detail.html'
    extra_context = {'title': 'Статья'}
    permission_required = ('blog.view_article',)

    def get_object(self, *args, **kwargs):
        self.object = super().get_object()
        self.object.views += 1
        self.object.save()
        return self.object


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Articles
    form_class = ArticleForm
    template_name = 'blog/article_form.html'
    extra_context = {"title": "Создание статьи"}
    login_url = reverse_lazy('users:login')
    permission_required = ('blog.add_articles',)

    def get_success_url(self):
        return reverse('blog:article', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    model = Articles
    template_name = 'blog/article_confirm_delete.html'
    extra_context = {"title": "Удаление статьи"}
    success_url = reverse_lazy('blog:articles_list')
    login_url = reverse_lazy('users:login')
    permission_required = ('blog.delete_articles', 'blog.change_articles',)

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or (user.groups.filter(name='content_manager').exists() and object.author == user):
            return object
        else:
            raise PermissionDenied


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    model = Articles
    form_class = ArticleForm
    template_name = 'blog/article_form.html'
    extra_context = {"title": "Редактирование статьи"}
    login_url = reverse_lazy('users:login')
    permission_required = ('blog.change_articles',)

    def get_success_url(self):
        return reverse('blog:article', kwargs={'slug': self.object.slug})

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or (user.groups.filter(name='content_manager').exists() and object.author == user):
            return object
        else:
            raise PermissionDenied

apps/blog/templates/blog/article_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
{% load my_tags %}

<div class="container">
    <div class="row">
        <div class="col-xxl-3"></div>
        <div class="col-xxl-6 text-center justify-content-center">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                <p>Желаете удалить эту статью?</p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'blog:article' object.slug %}" class="btn btn-warning">Отмена</a>
            </form>
        </div>

        <div class="row">
            <div class="col-4">
                <div class="card">
                    {% if object.img %}
                    <img src="{{ object.img.url }}" class="img-fluid" alt="Responsive image" width="130%">
                    {% else %}
                    <div class="card-body">
                        Изображение отсутствует.
                    </div>
                    {% endif %}
                </div>
                <small class="text-muted">
                    Автор: {{ object.author.first_name }} {{ object.author.last_name }} {{object.author.middle_name }}
                </small><br>
                <small class="text-muted">Просмотров: {{ object.views }}</small><br>
                <small class="text-muted">Создано: {{ object.created_at }}</small><br>
                <small class="text-muted">В редакции от: {{ object.created_at }}</small>
            </div>

            <div class="col-8">
                <div class="card">
                    <div class="card-header text-center">
                        <p class="fs-5">{{ object.title }}</p>
                    </div>
                    <div class="card-body">
                        {{ object.text }}
                    </div>
                </div>
                <div class="col-xxl-4"></div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

apps/blog/templates/blog/article_detail.html
{% extends '../main/base.html' %}

{% block content %}

<div class="btn-group text-right" role="group" aria-label="Basic outlined button group">

    {% if perms.blog.change_articles and object.author == user %}
    <button type="button" class="btn btn-outline-primary">
        <a href="{% url 'blog:update_article' object.slug %}">Отредактировать</a>
    </button>
    {% endif %}
    {% if perms.blog.delete_articles and perms.blog.change_articles and object.author == user %}
    <button type="button" class="btn btn-outline-primary">
        <a href="{% url 'blog:delete_article' object.slug %}">Удалить</a>
    </button>
    {% endif %}

</div>

<div class="text-center">
    <h3>{{ object.title }}</h3>
</div>

<div class="clearfix">
    <div class="row">
        <div class="col-4">
            <div class="float-left mr-3 mb-3">
                <img src="{{ object.img.url }}" class="img-fluid" alt="Responsive image" width="130%">
                <small class="text-muted">
                    Автор: {{ object.author.first_name }} {{ object.author.last_name }} {{object.author.middle_name }}
                </small><br>
                <small class="text-muted">Просмотров: {{ object.views }}</small><br>
                <small class="text-muted">Создано: {{ object.created_at }}</small><br>
                <small class="text-muted">В редакции от: {{ object.created_at }}</small>
            </div>
        </div>
        <div class="col-8">
            <div class="lh-lg fs-5">
                {{ object.text }}
            </div>

        </div>
    </div>
</div>

{% endblock content %}

apps/blog/templates/blog/article_form.html
{% extends 'main\base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xxl-3"></div>
        <div class="col-xxl-5">
            <p class="fs-4 text-center">
                Форма {% if object %}редактирования{% else %}создания{% endif %} статьи
            </p>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn-outline-primary" type="submit">
                    {% if object %} Изменить {% else %} Добавить {% endif %}
                </button>
                {% if object %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'blog:article' object.pk %}'">
                    Отмена
                </button>
                {% else %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'blog:articles_list' %}'">
                    Отмена
                </button>
                {% endif %}
            </form>
        </div>
        <div class="col-xxl-4"></div>
    </div>
</div>

{% endblock content %}

apps/blog/templates/blog/articles_list.html
{% extends '../main/base.html' %}

{% block content %}

<div class="container">
    {% if perms.blog.add_articles %}
    <div class="text-right">
        <button type="button" class="btn btn-outline-primary shadow-sm">
            <a href="{% url 'blog:create_article' %}">Добавить новость</a>
        </button>
    </div>
    {% endif %}
    {% for article in object_list %}

    <div class="card">
        <div class="row g-0">
            <div class="col-5 col-sm-4">
                <img src="{{ article.img.url }}" class="img-fluid w-100" alt="card-horizontal-image">
            </div>
            <div class="col-7 col-sm-8">
                <div class="card-body">
                    <a href="{% url 'blog:article' article.slug %}" class="card-title">
                        <h5>{{ article.title }}</h5>
                    </a>
                    <p class="card-text">{{ article.text|truncatewords:50 }}</p>
                    <p class="card-text">
                        <small class="text-muted">
                            Автор: {{ article.author.first_name }} {{ article.author.last_name }} {{article.author.middle_name }}
                        </small><br>
                        <small class="text-muted">Просмотров: {{ article.views }}</small><br>
                        <small class="text-muted">Создано: {{ article.created_at }}</small><br>
                        <small class="text-muted">В редакции от: {{ article.created_at }}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock content %}