apps/clients/urls.py
from django.urls import path

from apps.newsletters.apps import NewsletterConfig
from apps.clients.views import (ClientsListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                                ClientDeleteView, AddClientsToNewsletterView)

app_name = NewsletterConfig.name

urlpatterns = [
    path('clients/', ClientsListView.as_view(), name='clients_list'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('newsletters/<int:newsletter_id>/add_clients/', AddClientsToNewsletterView.as_view(),
         name='add_clients'),
]

apps/messages_/urls.py
from django.urls import path
from apps.messages_.apps import MessagesConfig
from apps.messages_.views import MessagesListView, MessageCreateView, MessageDetailView, MessageDeleteView, \
    MessageUpdateView

app_name = MessagesConfig.name


urlpatterns = [
    path('messages/', MessagesListView.as_view(), name='messages_list'),

    path('messages/<int:pk>', MessageDetailView.as_view(), name='message'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/update/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('messages/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

]

apps/newsletters/urls.py
from django.urls import path

from apps.newsletters.apps import NewsletterConfig
from apps.newsletters.views import (NewslettersListView, NewsletterDetailView, NewsletterCreateView,
                                    NewsletterUpdateView, NewsletterDeleteView, set_newsletters_status)

app_name = NewsletterConfig.name


urlpatterns = [
    path('newsletters/', NewslettersListView.as_view(), name='newsletters_list'),
    path('newsletters/<int:pk>', NewsletterDetailView.as_view(), name='newsletter'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletters/update/<int:pk>/', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletters/delete/<int:pk>/', NewsletterDeleteView.as_view(), name='delete_newsletter'),
    path('setnewslettersstatus/<int:pk>/', set_newsletters_status, name='set_newsletters_status'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main')),
    path('', include('apps.blog.urls', namespace='blog')),
    path('', include('apps.newsletters.urls', namespace='newsletters')),
    path('', include('apps.users.urls', namespace='users')),
    path('', include('apps.clients.urls', namespace='clients')),
    path('', include('apps.messages_.urls', namespace='messages_')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/messages_/models.py
from django.db import models

from config import settings


NULLABLE = {'null': True, 'blank': True}


class Messages(models.Model):
    subject_letter = models.CharField(max_length=250, verbose_name='Тема письма')
    text_letter = models.TextField(verbose_name='Текст письма')
    img_letter = models.ImageField(upload_to='messages/message', **NULLABLE, verbose_name='Картинка письма')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.subject_letter}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'
        ordering = ['subject_letter']
        db_table = '_ms_messages'
        db_table_comment = "Письма"
        permissions = [
            ('view_all_messages', 'Can view all Письмо'),
        ]

apps/newsletters/models.py
from datetime import timedelta

from django.utils.translation import gettext as _

from django.db import models
from apps.clients.models import Clients
from apps.messages_.models import Messages

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Newsletters(models.Model):

    class StateOfMailing(models.TextChoices):
        CREATED = 'C', _("Создана")
        LAUNCHED = 'L', _("Запущена")
        FINISHED = 'F', _("Завершена")

    class PeriodicityOfMailing(models.TextChoices):
        ONCE_DAY = 'D', _("Ежедневно")
        ONCE_WEEK = 'W', _("Еженедельно")
        ONCE_MONTH = 'M', _("Ежемесячно")
        ONCE_YEAR = 'Y', _("Ежегодно")

    name_newsletter = models.CharField(max_length=100, verbose_name='Название рассылки')
    date_first_mailing = models.DateTimeField(verbose_name='Дата и время первой рассылки')
    frequency_mailing = models.CharField(max_length=1, default=PeriodicityOfMailing.ONCE_DAY,
                                         choices=PeriodicityOfMailing, verbose_name='Периодичность рассылки')
    date_next_mailing = models.DateTimeField(**NULLABLE, verbose_name='Дата и время следующей рассылки')
    state_mailing = models.CharField(max_length=1, default=StateOfMailing.CREATED, choices=StateOfMailing,
                                     verbose_name='Состояние рассылки')
    clients = models.ManyToManyField(Clients, related_name='clients')
    message = models.ForeignKey(Messages, on_delete=models.CASCADE, verbose_name='Сообщение')
    is_active = models.BooleanField(default=True, verbose_name='Статус рассылки')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.name_newsletter}'

    def save(self, *args, **kwargs):
        if not self.date_next_mailing:
            if self.frequency_mailing == self.PeriodicityOfMailing.ONCE_DAY:
                self.date_next_mailing = self.date_first_mailing + timedelta(days=1)
            elif self.frequency_mailing == self.PeriodicityOfMailing.ONCE_WEEK:
                self.date_next_mailing = self.date_first_mailing + timedelta(days=7)
            elif self.frequency_mailing == self.PeriodicityOfMailing.ONCE_MONTH:
                self.date_next_mailing = self.date_first_mailing + timedelta(days=30)
            else:
                self.date_next_mailing = self.date_first_mailing + timedelta(days=365)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['date_first_mailing', 'name_newsletter']
        db_table = '_ns_newsletters'
        db_table_comment = "Рассылки"
        permissions = [
            ('set_newsletters_deactivate', 'Can deacticate Рассылка'),
            ('view_all_newsletters', 'Can view all Рассылка'),
        ]


class Logs(models.Model):

    class StatusOfLogs(models.TextChoices):
        SUCCESS = "Успешно", _("Успешно")
        FAILED = "Безуспешно", _("Безуспешно")
        PARTIALLY = "Частично успешно", _("Частично успешно")

    newsletter = models.ForeignKey(Newsletters, on_delete=models.CASCADE, related_name='logs')
    date_last_mailing = models.DateTimeField(verbose_name='Дата последней попытки')
    status_mailing = models.CharField(choices=StatusOfLogs, verbose_name='Статус рассылки')
    response_mail_server = models.TextField(**NULLABLE, verbose_name='Ответ почтового сервера')

    def __str__(self):
        return f'{self.newsletter} {self.status_mailing}'

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'
        ordering = ['newsletter', 'date_last_mailing']
        db_table = '_ns_logs'
        db_table_comment = "Попытки рассылки"

apps/newsletters/forms.py
from apps.clients.models import Clients
from apps.messages_.models import Messages
from apps.newsletters.models import Newsletters
from django import forms
from core.forms import StyleFormMixin


class NewsletterForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, owner, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name_newsletter'].widget.attrs.update({'class': 'form-control'})
        self.fields['message'].queryset = Messages.objects.filter(owner=owner)
        self.fields['clients'].queryset = Clients.objects.filter(owner=owner)

    class Meta:
        model = Newsletters
        exclude = ('owner', 'date_next_mailing')

apps/newsletters/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404

from apps.clients.models import Clients
from apps.newsletters.forms import NewsletterForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from apps.newsletters.models import Newsletters
from django.urls import reverse, reverse_lazy

from apps.users.models import Users


class NewslettersListView(PermissionRequiredMixin, ListView):
    model = Newsletters
    template_name = 'newsletters/newsletters_list.html'
    extra_context = {'title': 'Рассылки'}
    login_url = reverse_lazy('users:login')
    permission_required = ('newsletters.view_newsletters',)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or user.has_perm('newsletters.view_all_newsletters'):
            return queryset
        else:
            queryset = queryset.filter(owner=user)
            return queryset


class NewsletterDetailView(PermissionRequiredMixin, DetailView):
    model = Newsletters
    template_name = 'newsletters/newsletter_detail.html'
    extra_context = {'title': 'Рассылка'}
    login_url = reverse_lazy('users:login')
    permission_required = ('newsletters.view_newsletters',)

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists() or object.owner == user:
            return object
        else:
            raise PermissionDenied


class NewsletterCreateView(PermissionRequiredMixin, CreateView):
    model = Newsletters
    form_class = NewsletterForm
    template_name = 'newsletters/newsletter_form.html'
    extra_context = {'title': 'Добавить рассылку'}
    login_url = reverse_lazy('users:login')
    permission_required = ('newsletters.add_newsletters',)

    def get_success_url(self):
        return reverse('newsletters:newsletter', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        data = super().get_form_kwargs()
        data['owner'] = self.request.user
        return data

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Clients.objects.filter(owner=self.request.user)
        return form


class NewsletterUpdateView(PermissionRequiredMixin, UpdateView):
    model = Newsletters
    form_class = NewsletterForm
    template_name = 'newsletters/newsletter_form.html'
    extra_context = {'title': 'Изменить рассылку'}
    login_url = reverse_lazy('users:login')
    permission_required = ('newsletters.change_newsletters',)

    def get_success_url(self):
        return reverse('newsletters:newsletter', kwargs={'pk': self.object.pk})

    def get_form_kwargs(self):
        data = super().get_form_kwargs()
        data['owner'] = self.request.user
        return data

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.owner == user:
            return object
        else:
            raise PermissionDenied


class NewsletterDeleteView(PermissionRequiredMixin, DeleteView):
    model = Newsletters
    template_name = 'newsletters/newsletter_confirm_delete.html'
    extra_context = {'title': 'Удалить рассылку'}
    success_url = reverse_lazy('newsletters:newsletters_list')
    login_url = reverse_lazy('users:login')
    permission_required = ('newsletters.delete_newsletters', 'newsletters.change_newsletters',)

    def get_object(self, *args, **kwargs):
        object = super().get_object(*args, **kwargs)
        user = self.request.user
        if user.is_superuser or object.owner == user:
            return object
        else:
            raise PermissionDenied


def set_newsletters_status(request, pk):
    """Контроллер изменения статуса рассылки"""
    if request.user.is_superuser or request.user.groups.filter(name='manager').exists():
        newsletter = Newsletters.objects.get(pk=pk)
        newsletter.is_active = not newsletter.is_active
        newsletter.save()
        return redirect(reverse('newsletters:newsletter', kwargs={'pk': newsletter.pk}))

apps/newsletters/templates/newsletters/newsletter_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
{% load my_tags %}
<div class="container">
    <div class="row justify-content-center text-center">
        <div class="col-7">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                <p>
                    Желаете удалить рассылку {{ object.name_newsletter }}?
                </p>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'newsletters:newsletter' object.pk %}" class="btn btn-warning">Отмена</a>
            </form>
        </div>

        <div class="col-7">
            <div class="card">
                <div class="card-body text-start">
                    <ul>
                        <li><a>Название рассылки: {{ object.name_newsletter }}</a></li>
                        <li><a>Дата первой рассылки: {{ object.date_first_mailing }}</a></li>
                        <li><a>Периодичность рассылки: {{ object.frequency_mailing|compare_periodicity }}</a></li>
                        <li><a>Состояние рассылки: {{ object.state_mailing|compare_status }}</a></li>
                        <li><a>Статус рассылки: {{ object.is_active|yesno:"Активна,Не активна" }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xxl-4"></div>
        </div>
    </div>
    <div class="col-xxl-3"></div>
</div>

{% endblock %}

apps/newsletters/templates/newsletters/newsletter_detail.html
{% extends '../main/base.html' %}
{% load my_tags %}

{% block content %}

<!--Блок основной информации о рассылке-->
<div class="container">
    <div class="row">
        <div class="col-9 ">
            <ul>
                <li><a>Название рассылки: {{ object.name_newsletter }}</a></li>
                <li><a>Дата первой рассылки: {{ object.date_first_mailing }}</a></li>
                <li><a>Периодичность рассылки: {{ object.frequency_mailing|compare_periodicity }}</a></li>
                <li><a>Состояние рассылки: {{ object.state_mailing|compare_status }}</a></li>
                <li><a>Статус рассылки: {{ object.is_active|yesno:"Активна,Не активна" }}</a></li>
            </ul>

            <div class="justify-content-end">
                <div class="btn-group mb-2" role="group" aria-label="Basic outlined button group">

                    {% if perms.newsletters.change_newsletters and user == object.owner %}
                    <button type="button" class="btn btn-outline-primary shadow-sm">
                        <a href="{% url 'newsletters:update_newsletter' object.pk %}">Редактировать</a>
                    </button>
                    {% endif %}

                    {% if perms.newsletters.delete_newsletters and user == object.owner %}
                    <button type="button" class="btn btn-outline-primary shadow-sm">
                        <a href="{% url 'newsletters:delete_newsletter' object.pk %}">Удалить</a>
                    </button>
                    {% endif %}

                    {% if perms.newsletters.set_newsletters_deactivate %}
                    <button type="submit" class="btn btn-outline-primary shadow-sm">
                        <a href="{% url 'newsletters:set_newsletters_status' object.pk %}">
                            {% if user.is_active %} Деактивировать {% else %} Активировать {% endif %}
                        </a>
                    </button>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>


    <!--Блок с вкладками с дополнительной информацией о рассылке-->
    <div class="container">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="clients-tab" data-bs-toggle="tab" href="#clients" role="tab"
                           aria-controls="clients" aria-selected="true">Клиенты</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="messages-tab" data-bs-toggle="tab" href="#messages" role="tab"
                           aria-controls="messages" aria-selected="false">Сообщение</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="history-tab" data-bs-toggle="tab" href="#history" role="tab"
                           aria-controls="history" tabindex="-1" aria-disabled="true">История рассылок</a>
                    </li>
                </ul>
            </div>
            <div class="card-body">
                <div class="tab-content" id="myTabContent">

                    <!--            Блок с информацией о клиентах-->
                    <div class="tab-pane fade show active" id="clients" role="tabpanel" aria-labelledby="clients-tab">

                        <div class="btn-group" role="group" aria-label="Basic outlined button group">
                            {% if perms.newsletters.change_newsletters and user == object.owner %}
                            <button type="button" class="btn btn-outline-primary shadow-sm">
                                <a href="{% url 'newsletters:update_newsletter' object.pk %}"
                                   style="color: black; text-decoration: none;">Добавить</a>
                            </button>
                            {% endif %}
                            {% if perms.clients.add_clients and user == object.owner %}
                            <button type="button" class="btn btn-outline-primary shadow-sm">
                                <a href="{% url 'clients:create_client' %}"
                                   style="color: black; text-decoration: none;">Создать клиента</a>
                            </button>
                            {% endif %}
                        </div>

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">№</th>
                                <th scope="col">Имя Фамилия Отчество</th>
                                <th scope="col">Email</th>
                                <th scope="col">Дата рождения</th>
                                <th scope="col">Комментарий</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for client in object.clients.all %}

                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>
                                    <a href="{% url 'clients:client' client.pk %}">
                                        {{ client.first_name }} {{ client.last_name }} {{ client.middle_name }}
                                    </a>
                                </td>
                                <td>{{ client.email }}</td>
                                <td>{{ client.birthday }}</td>
                                <td>{{ client.comment }}</td>
                            </tr>
                            {% empty %}
                            <p>Нет клиентов</p>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>

                    <!--            Блок с информацией о сообщениях-->
                    <div class="tab-pane fade" id="messages" role="tabpanel" aria-labelledby="messages-tab">
                        <div class="">
                            <div class="btn-group" role="group" aria-label="Basic outlined button group">
                                {% if perms.messages_.add_messages and user == object.owner %}
                                <button type="button" class="btn btn-outline-primary">
                                    <a href="{% url 'messages_:create_message' %}">Создать сообщение</a>
                                </button>
                                {% endif %}
                                {% if perms.messages_.change_messages and user == object.owner %}
                                <button type="button" class="btn btn-outline-primary">
                                    <a href="{% url 'messages_:update_message' object.message.pk %}">
                                        Редактировать активное сообщение
                                    </a>
                                </button>
                                {% endif %}


                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.message }}</h5>
                                <p class="card-text">
                                    {{ object.message.text_letter }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <!--            Блок с информацией об истории рассылки-->
                    <div class="tab-pane fade" id="history" role="tabpanel" aria-labelledby="history-tab">
                        Попытки рассылки
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Дата рассылки</th>
                                <th scope="col">Статус рассылки</th>
                                <th scope="col">Отчет о рассылке</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for log in object.logs.all %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ log.date_last_mailing }}</td>
                                <td>{{ log.status_mailing }}</td>
                                <td>{{ log.response_mail_server }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endblock content %}

apps/newsletters/templates/newsletters/newsletter_form.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xxl-3"></div>
        <div class="col-xxl-5">
            <p class="fs-4 text-center">
                Форма {% if object %}редактирования{% else %}создания{% endif %} рассылки
            </p>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn-outline-primary" type="submit">
                    {% if object %} Изменить {% else %} Добавить {% endif %}
                </button>
                {% if object %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'newsletters:newsletter' object.pk %}'">
                    Отмена
                </button>
                {% else %}
                <button class="btn-outline-primary" type="button"
                        onclick="window.location.href='{% url 'newsletters:newsletters_list' %}'">
                    Отмена
                </button>
                {% endif %}
            </form>
        </div>
        <div class="col-xxl-4"></div>
    </div>
</div>

{% endblock content %}

apps/newsletters/templates/newsletters/newsletters_list.html
{% extends '../main/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    {% if perms.newsletters.add_newsletters %}
    <div class="text-right">
        <button type="button" class="btn btn-outline-primary shadow-sm">
            <a href="{% url 'newsletters:create_newsletter' %}" style="color: black; text-decoration: none;">Создать рассылку</a>
        </button>
    </div>
    {% endif %}

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название рассылки</th>
            <th scope="col">Дата первой рассылки</th>
            <th scope="col">Периодичность рассылки</th>
            <th scope="col">Состояние рассылки</th>
            <th scope="col">Статус рассылки</th>
            <th scope="col">Владелец</th>
        </tr>
        </thead>
        <tbody>

        {% for object in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'newsletters:newsletter' object.pk %}">{{ object.name_newsletter }}</a></td>
            <td>{{ object.date_first_mailing }}</td>
            <td>{{ object.frequency_mailing|compare_periodicity }}</td>
            <td>{{ object.state_mailing|compare_status }}</td>
            <td>
                {{ object.is_active|yesno:"Активна,Не активна" }}
            </td>
            <td>{{ object.owner }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}